// Generated by CoffeeScript 1.7.1
(function() {
  var Citero, java, root;

  java = require("java");

  java.classpath.push("" + __dirname + "/citero.jar");

  Citero = (function() {
    function Citero(data) {
      this.cite = java["import"]("edu.nyu.library.citero.Citero");
      this.cite = this.cite.mapSync(data);
      this;
    }

    Citero.map = function(data) {
      return new this(data);
    };

    Citero.prototype.from = function(format) {
      this.cite.fromSync(format);
      return this;
    };

    Citero.prototype.to = function(format) {
      return this.cite.toSync(format);
    };

    return Citero;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Citero = Citero;

  root.Formats = require("./formats").Formats;

}).call(this);
