// Generated by CoffeeScript 1.7.1
(function() {
  var Formats, java, root;

  java = require("java");

  java.classpath.push("" + __dirname + "/citero.jar");

  Formats = java["import"]("edu.nyu.library.citero.Formats");

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Formats = Formats;

}).call(this);
